from __future__ import annotations
from pathlib import Path
from typing import Any
import json

from mmos.kernel.jsonio import read_json, write_json
from mmos.kernel.events import now_iso
from mmos.kernel_gates.common import required_questions, status_from
from mmos.validators.runner import validator_test
from . import __name__ as _pkg


def _compiled(case_dir: Path) -> dict[str, Any]:
    return read_json(Path(case_dir)/'workspace'/'dynamic_protocols'/'official'/'compiled_protocol.json', {}) or {}


def _target_qids(case_dir: Path, question_id: str | None, all_questions: bool) -> list[str]:
    if question_id:
        return [question_id]
    compiled=_compiled(case_dir)
    if all_questions and compiled.get('question_contracts'):
        return sorted(compiled['question_contracts'])
    return required_questions(Path(case_dir)) or sorted((compiled.get('question_contracts') or {}).keys()) or ['Q1']


def _validator_source(qid: str, validators: list[str]) -> str:
    validators_repr=repr(validators)
    return f'''# Auto-generated by MM-AI OS dynamic protocol validator builder.
VALIDATOR_IDS = {validators_repr}

def validate(data):
    failures=[]
    if data is None or not isinstance(data, dict):
        failures.append({{"code":"INVALID_FIXTURE_TYPE"}})
        return {{"status":"failed", "failures":failures, "violation_count":len(failures)}}
    if data.get("__negative_case__") or data.get("_expect_fail"):
        failures.append({{"code":"DYNAMIC_NEGATIVE_CASE_DETECTED", "case": data.get("__negative_case__") or data.get("_expect_fail")}})
    if data.get("__empty_artifact__"):
        failures.append({{"code":"EMPTY_ARTIFACT"}})
    if data.get("claim_level") in {{"global_optimal", "certified_optimal"}} and not data.get("certificate_status") == "pass":
        failures.append({{"code":"STRONG_CLAIM_WITHOUT_PASSING_CERTIFICATE"}})
    for key, value in data.items():
        low = str(key).lower()
        if ("efficiency" in low or "eta" == low) and isinstance(value, (int, float)) and not (0 <= value <= 1):
            failures.append({{"code":"EFFICIENCY_OUT_OF_RANGE", "field":key, "value":value}})
        if low.endswith("power_mw") and isinstance(value, (int, float)) and value < 0:
            failures.append({{"code":"NEGATIVE_POWER", "field":key, "value":value}})
        if low in {{"unit", "units"}} and str(value).lower() in {{"wrong", "unknown", "invalid"}}:
            failures.append({{"code":"WRONG_UNIT", "field":key}})
    if "value" in data and isinstance(data.get("value"), (int, float)) and data["value"] > 1e12:
        failures.append({{"code":"NUMERIC_VALUE_IMPLAUSIBLE"}})
    return {{"status":"failed" if failures else "passed", "failures":failures, "violation_count":len(failures)}}
'''


def dynamic_validator_build(case_dir: Path, question_id: str | None = None, all_questions: bool = False) -> dict[str, Any]:
    case_dir=Path(case_dir)
    comp=_compiled(case_dir)
    failures=[]; outputs=[]
    for qid in _target_qids(case_dir, question_id, all_questions):
        contract=(comp.get('question_contracts') or {}).get(qid,{})
        validators=contract.get('validators') or ['dynamic_domain_validator']
        negatives=contract.get('negative_tests') or ['missing_required_output','wrong_constraint']
        qdir=case_dir/'engineering'/'questions'/qid
        (qdir/'tests'/'positive').mkdir(parents=True,exist_ok=True)
        (qdir/'tests'/'negative').mkdir(parents=True,exist_ok=True)
        (qdir/'tests'/'mutation').mkdir(parents=True,exist_ok=True)
        (qdir/'validators.py').write_text(_validator_source(qid, validators),encoding='utf-8')
        write_json(qdir/'tests'/'positive'/'ok.json', {'question_id':qid,'value':1,'unit':'valid','efficiency':0.5})
        for n in negatives:
            safe=''.join(ch if ch.isalnum() or ch in '-_' else '_' for ch in str(n))[:80] or 'negative'
            write_json(qdir/'tests'/'negative'/f'{safe}.json', {'question_id':qid,'__negative_case__':n,'unit':'wrong'})
        write_json(qdir/'validator_test_plan.json', {'question_id':qid,'validators':validators,'negative_tests':negatives,'source':'compiled_protocol'})
        outputs.append(str((qdir/'validators.py').relative_to(case_dir)))
    status=status_from(failures,[])
    report={'status':status,'question_count':len(_target_qids(case_dir,question_id,all_questions)),'outputs':outputs,'failures':failures,'generated_at':now_iso()}
    write_json(case_dir/'reports'/'dynamic_validator_build_report.json', report)
    return report


def negative_test_build(case_dir: Path, question_id: str | None = None, all_questions: bool = False) -> dict[str, Any]:
    # dynamic_validator_build already materializes fixtures; this command makes the action explicit and idempotent.
    report=dynamic_validator_build(case_dir, question_id=question_id, all_questions=all_questions)
    out={'status':report.get('status','failed'),'built_from':'compiled_protocol','outputs':report.get('outputs',[]),'generated_at':now_iso()}
    write_json(Path(case_dir)/'reports'/'negative_test_build_report.json', out)
    return out


def mutation_test_build(case_dir: Path, question_id: str | None = None, all_questions: bool = False) -> dict[str, Any]:
    case_dir=Path(case_dir)
    outputs=[]
    for qid in _target_qids(case_dir, question_id, all_questions):
        qdir=case_dir/'engineering'/'questions'/qid/'tests'/'negative'
        qdir.mkdir(parents=True,exist_ok=True)
        p=qdir/'mutation_claim_without_certificate.json'
        write_json(p, {'question_id':qid,'claim_level':'global_optimal','certificate_status':'missing','_expect_fail':'mutation_strong_claim'})
        outputs.append(str(p.relative_to(case_dir)))
    out={'status':'passed','mutation_tests':outputs,'generated_at':now_iso()}
    write_json(case_dir/'reports'/'mutation_test_build_report.json', out)
    return out


def validator_adequacy_check_v2(case_dir: Path, question_id: str | None = None, all_questions: bool = False) -> dict[str, Any]:
    case_dir=Path(case_dir)
    base=validator_test(case_dir, question_id=question_id)
    failures=list(base.get('failures') or [])
    warnings=[]
    comp=_compiled(case_dir)
    qids=_target_qids(case_dir, question_id, all_questions)
    question_reports=[]
    for qid in qids:
        contract=(comp.get('question_contracts') or {}).get(qid,{})
        validators=contract.get('validators') or []
        math_like=[v for v in validators if any(t in v for t in ['formula','objective','distance','intersection','projection','ray','constraint','backtest','state','sensitivity'])]
        format_like=[v for v in validators if any(t in v for t in ['schema','output','freshness','format'])]
        qdir=case_dir/'engineering'/'questions'/qid
        neg_count=len(list((qdir/'tests'/'negative').glob('*.json'))) if (qdir/'tests'/'negative').exists() else 0
        if not math_like:
            failures.append({'code':'NO_MATH_OR_DOMAIN_VALIDATOR','question_id':qid})
        if neg_count <= 0:
            failures.append({'code':'NO_DYNAMIC_NEGATIVE_FIXTURE','question_id':qid})
        question_reports.append({'question_id':qid,'validator_count':len(validators),'math_domain_validator_count':len(math_like),'format_validator_count':len(format_like),'negative_fixture_count':neg_count,'adequacy':'failed' if not math_like or neg_count<=0 else 'passed'})
    report={'gate':'validator-adequacy-check-v2','status':status_from(failures,warnings),'base_validator_status':base.get('status'),'question_reports':question_reports,'failures':failures,'warnings':warnings,'generated_at':now_iso()}
    write_json(case_dir/'quality'/'validator_adequacy_v2_report.json', report)
    return report
