
from __future__ import annotations

import argparse

from .commands_case import *
from .commands_contracts import *
from .commands_runtime import *
from .commands_artifacts import *
from .commands_research import *
from .commands_quality import *
from .commands_paper import *
from .commands_agent import *
from .commands_competition import *
from .commands_chart import *
from .commands_schema import *
from .commands_synthetic import *
from .commands_agent_runtime import *
from .commands_modeling_os import *

def build_parser():
    p = argparse.ArgumentParser(prog='mmtool.py', description='MM-AI OS v11.0.0 Dynamic Protocol Certified Modeling Stable CLI')
    p.add_argument('--strict-warnings-exit', action='store_true', help='return non-zero for JSON status=warning as well as failed')
    sub = p.add_subparsers(dest='cmd', required=True)
    s = sub.add_parser('schema-list'); s.set_defaults(fn=cmd_schema_list)
    s = sub.add_parser('schema-validate'); s.add_argument('--schema', required=True); s.add_argument('--file', required=True); s.set_defaults(fn=cmd_schema_validate)

    s = sub.add_parser('artifact-init-layout'); s.add_argument('case'); s.set_defaults(fn=cmd_artifact_init_layout)
    s = sub.add_parser('artifact-promote'); s.add_argument('case'); s.add_argument('--source', required=True); s.add_argument('--destination', required=True); s.add_argument('--schema'); s.add_argument('--mirror-legacy'); s.set_defaults(fn=cmd_artifact_promote)
    s = sub.add_parser('artifact-migrate-layout'); s.add_argument('case'); s.add_argument('--overwrite', action='store_true'); s.set_defaults(fn=cmd_artifact_migrate_layout)
    s = sub.add_parser('agent-write-check'); s.add_argument('case'); s.add_argument('--path', required=True); s.set_defaults(fn=cmd_agent_write_check)

    s = sub.add_parser('synthetic-install'); s.add_argument('case'); s.add_argument('--overwrite', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_synthetic_install)
    s = sub.add_parser('synthetic-search-inject'); s.add_argument('case'); s.add_argument('--question'); s.set_defaults(fn=cmd_synthetic_search_inject)
    s = sub.add_parser('synthetic-solution-inject'); s.add_argument('case'); s.add_argument('--question', default='Q1'); s.set_defaults(fn=cmd_synthetic_solution_inject)
    s = sub.add_parser('synthetic-write-golden'); s.add_argument('case'); s.add_argument('--destination', required=True); s.set_defaults(fn=cmd_synthetic_write_golden)
    s = sub.add_parser('synthetic-e2e-run'); s.add_argument('case'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_synthetic_e2e_run)

    s = sub.add_parser('workflow-state'); s.add_argument('case'); s.set_defaults(fn=cmd_workflow_state)
    s = sub.add_parser('workflow-transition'); s.add_argument('case'); s.add_argument('--step', required=True); s.add_argument('--status'); s.set_defaults(fn=cmd_workflow_transition)
    s = sub.add_parser('agent-policy-init'); s.add_argument('case'); s.set_defaults(fn=cmd_agent_policy_init)
    s = sub.add_parser('agent-runtime-report'); s.add_argument('case'); s.add_argument('--latest', action='store_true'); s.add_argument('--task-id', default='manual'); s.add_argument('--role', default='deterministic_agent'); s.add_argument('--context-file', action='append'); s.add_argument('--candidate-output', action='append'); s.add_argument('--command', action='append'); s.set_defaults(fn=cmd_agent_runtime_report)
    s = sub.add_parser('agent-budget-check'); s.add_argument('case'); s.add_argument('--context-files', type=int, default=0); s.add_argument('--tool-calls', type=int, default=0); s.add_argument('--search-queries', type=int, default=0); s.add_argument('--runtime-seconds', type=int, default=0); s.add_argument('--candidate-outputs', type=int, default=0); s.set_defaults(fn=cmd_agent_budget_check)
    s = sub.add_parser('mcp-permission-check'); s.add_argument('case'); s.add_argument('--tool', required=True); s.add_argument('--target'); s.add_argument('--mode', default='read'); s.set_defaults(fn=cmd_mcp_permission_check)

    s = sub.add_parser('case-init'); s.add_argument('case'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_case_init)
    s = sub.add_parser('ingest-documents'); s.add_argument('case'); s.add_argument('--unpack-archives', action='store_true'); s.set_defaults(fn=cmd_ingest)
    s = sub.add_parser('problem-parse'); s.add_argument('case'); s.set_defaults(fn=cmd_parse)

    s = sub.add_parser('data-audit'); s.add_argument('case'); s.add_argument('--recursive', action='store_true'); s.add_argument('--manifest', action='store_true'); s.set_defaults(fn=cmd_data_audit)
    s = sub.add_parser('problem-graph-build'); s.add_argument('case'); s.set_defaults(fn=cmd_problem_graph_build)
    s = sub.add_parser('output-register-draft'); s.add_argument('case'); s.add_argument('--accept', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_output_register_draft)
    s = sub.add_parser('output-build'); s.add_argument('case'); s.add_argument('--all-required', action='store_true', default=True); s.add_argument('--accept-draft', action='store_true'); s.set_defaults(fn=cmd_output_build)
    s = sub.add_parser('package-case'); s.add_argument('case'); s.add_argument('--allow-warnings', action='store_true'); s.set_defaults(fn=cmd_package_case)
    s = sub.add_parser('academic-search'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--budget', default='full'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_academic_search)
    s = sub.add_parser('method-match'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_method_match)
    s = sub.add_parser('method-recommend'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--budget', default='full'); s.set_defaults(fn=cmd_method_recommend)
    s = sub.add_parser('question-activate'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--type', default='generic_optimization'); s.add_argument('--title'); s.add_argument('--required', action=argparse.BooleanOptionalAction, default=None); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_question_activate)
    s = sub.add_parser('contract-build'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--type'); s.add_argument('--title'); s.add_argument('--force', action='store_true'); s.add_argument('--from', dest='from_source'); s.add_argument('--from-compiled-protocol', dest='from_compiled_protocol', action='store_true'); s.set_defaults(fn=cmd_contract_build)
    s = sub.add_parser('contract-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_contract_check)
    s = sub.add_parser('missing-info-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_missing_info)
    s = sub.add_parser('question-run-stage'); s.add_argument('case'); s.add_argument('--question', required=True); s.add_argument('--stage', required=True); s.add_argument('--budget', default='regression'); s.add_argument('--resume', action='store_true'); s.set_defaults(fn=cmd_stage)
    s = sub.add_parser('question-run-flow'); s.add_argument('case'); s.add_argument('--question', required=True); s.add_argument('--execute', action='store_true'); s.add_argument('--resume', action='store_true'); s.add_argument('--budget', default='regression'); s.set_defaults(fn=cmd_question_flow)
    s = sub.add_parser('case-run-flow'); s.add_argument('case'); s.add_argument('--execute', action='store_true'); s.add_argument('--resume', action='store_true'); s.add_argument('--budget', default='regression'); s.set_defaults(fn=cmd_case_flow)
    s = sub.add_parser('output-discover'); s.add_argument('case'); s.add_argument('--write-draft', action='store_true'); s.set_defaults(fn=cmd_output_discover)
    s = sub.add_parser('output-validate'); s.add_argument('case'); s.add_argument('--semantic', action='store_true'); s.add_argument('--freshness', action='store_true'); s.add_argument('--all-required', action='store_true'); s.set_defaults(fn=cmd_output_validate)
    s = sub.add_parser('solver-verify'); s.add_argument('case'); s.add_argument('--result'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action='store_true'); s.add_argument('--strict-schema', action='store_true'); s.set_defaults(fn=cmd_solver_verify)
    s = sub.add_parser('placeholder-scan'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_placeholder_scan)
    s = sub.add_parser('constraint-test'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_constraint_test)
    s = sub.add_parser('stale-output-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_stale_output_check)
    s = sub.add_parser('report-consistency-check'); s.add_argument('case'); s.add_argument('--report'); s.add_argument('--abs-tol', type=float, default=1e-4); s.add_argument('--rel-tol', type=float, default=1e-3); s.set_defaults(fn=cmd_report_consistency)
    s = sub.add_parser('evidence-pack'); s.add_argument('case'); s.add_argument('--question'); s.set_defaults(fn=cmd_evidence_pack)
    s = sub.add_parser('run-report'); s.add_argument('case'); s.add_argument('--latest', action='store_true'); s.add_argument('--run-id'); s.set_defaults(fn=cmd_run_report)
    s = sub.add_parser('case-status'); s.add_argument('case'); s.set_defaults(fn=cmd_case_status)
    s = sub.add_parser('backlog-build'); s.add_argument('case'); s.set_defaults(fn=cmd_backlog)
    s = sub.add_parser('self-test'); s.add_argument('--case', default='selftest_v52'); s.add_argument('--budget', default='fast'); s.set_defaults(fn=cmd_self_test)
    s = sub.add_parser('fixture-run'); s.add_argument('--budget', default='regression'); s.set_defaults(fn=cmd_fixture_run)

    s = sub.add_parser('method-candidates'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_method_candidates)
    s = sub.add_parser('model-maturity-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_model_maturity)
    s = sub.add_parser('bound-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_bound_check)
    s = sub.add_parser('independent-verify'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--abs-tol', type=float, default=1e-6); s.add_argument('--rel-tol', type=float, default=0.05); s.set_defaults(fn=cmd_independent_verify)
    s = sub.add_parser('sensitivity-analysis'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--budget', default='regression'); s.set_defaults(fn=cmd_sensitivity)
    s = sub.add_parser('solver-tournament'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--budget', default='regression'); s.add_argument('--min-candidates', type=int, default=3); s.set_defaults(fn=cmd_solver_tournament)
    s = sub.add_parser('red-team-review'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_red_team)
    s = sub.add_parser('quality-oracle'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_quality_oracle)
    s = sub.add_parser('solution-improve'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--rounds', type=int, default=3); s.add_argument('--budget', default='regression'); s.set_defaults(fn=cmd_solution_improve)

    s = sub.add_parser('problem-parse-v2'); s.add_argument('case'); s.set_defaults(fn=cmd_problem_parse_v2)
    s = sub.add_parser('problem-parse-v3'); s.add_argument('case'); s.set_defaults(fn=cmd_problem_parse_v2)
    s = sub.add_parser('problem-signature-extract'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_problem_signature_extract)
    s = sub.add_parser('problem-understand'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=False); s.set_defaults(fn=cmd_problem_understand)
    s = sub.add_parser('understanding-gate'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_understanding_gate)
    s = sub.add_parser('search-plan-gate'); s.add_argument('case'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_search_plan_gate)
    s = sub.add_parser('method-plan-synthesize'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_method_plan_synthesize)
    s = sub.add_parser('method-plan-approve'); s.add_argument('case'); s.add_argument('--question', required=True); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_method_plan_approve)
    s = sub.add_parser('method-plan-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_method_plan_check)
    s = sub.add_parser('coverage-gap-analysis'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_coverage_gap_analysis)
    s = sub.add_parser('citation-validate'); s.add_argument('case'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_citation_validate)
    s = sub.add_parser('semantic-audit'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_semantic_audit)
    s = sub.add_parser('method-plan'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_method_plan)
    s = sub.add_parser('claim-evidence-plan'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_claim_evidence_plan)
    s = sub.add_parser('claim-evidence-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_claim_evidence_check)
    s = sub.add_parser('pdf-text-check'); s.add_argument('case'); s.set_defaults(fn=cmd_pdf_text_check)
    s = sub.add_parser('paper-argument-check'); s.add_argument('case'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_paper_argument_check)
    s = sub.add_parser('paper-evidence-check'); s.add_argument('case'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_paper_evidence_check)
    s = sub.add_parser('figure-argument-check'); s.add_argument('case'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_figure_argument_check)
    s = sub.add_parser('submission-gate-check'); s.add_argument('case'); s.add_argument('--allow-warnings', action='store_true'); s.set_defaults(fn=cmd_submission_gate)
    s = sub.add_parser('award-readiness-check'); s.add_argument('case'); s.add_argument('--target', default='national_first'); s.add_argument('--strict-submission', action='store_true'); s.set_defaults(fn=cmd_award_readiness)
    s = sub.add_parser('repair-plan'); s.add_argument('case'); s.set_defaults(fn=cmd_repair_plan)
    s = sub.add_parser('repair-task-generate'); s.add_argument('case'); s.set_defaults(fn=cmd_repair_task_generate)
    s = sub.add_parser('temporal-semantics-extract'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_temporal_semantics_extract)
    s = sub.add_parser('temporal-semantics-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_temporal_semantics_check)
    s = sub.add_parser('attachment-semantic-audit'); s.add_argument('case'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_attachment_semantic_audit)
    s = sub.add_parser('model-fidelity-plan'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_model_fidelity_plan)
    s = sub.add_parser('model-fidelity-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_model_fidelity_check)
    s = sub.add_parser('solver-variant-verify'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_solver_variant_verify)

    s = sub.add_parser('paper-readiness-gate'); s.add_argument('case'); s.add_argument('--target', default='national_first'); s.set_defaults(fn=cmd_paper_readiness_gate)
    s = sub.add_parser('paper-evidence-graph'); s.add_argument('case'); s.add_argument('--build', action='store_true', default=True); s.set_defaults(fn=cmd_paper_evidence_graph)
    s = sub.add_parser('paper-argument-plan-v61'); s.add_argument('case'); s.add_argument('--target', default='national_first'); s.set_defaults(fn=cmd_paper_argument_plan_v61)
    s = sub.add_parser('figure-table-plan'); s.add_argument('case'); s.add_argument('--target', default='national_first'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_figure_table_plan)
    s = sub.add_parser('appendix-code-build'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_appendix_code_build)
    s = sub.add_parser('appendix-code-check'); s.add_argument('case'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_appendix_code_check)
    s = sub.add_parser('paper-redteam-review'); s.add_argument('case'); s.add_argument('--target', default='national_first'); s.set_defaults(fn=cmd_paper_redteam_review_v61)
    s = sub.add_parser('paper-repair-dispatch'); s.add_argument('case'); s.set_defaults(fn=cmd_paper_repair_dispatch)
    s = sub.add_parser('paper-env-doctor'); s.add_argument('case', nargs='?'); s.set_defaults(fn=cmd_paper_env_doctor)
    s = sub.add_parser('latex-paper-build'); s.add_argument('case'); s.add_argument('--force', action='store_true'); s.add_argument('--template', default='cumcm_gold'); s.set_defaults(fn=cmd_latex_paper_build)
    s = sub.add_parser('latex-paper-compile'); s.add_argument('case'); s.add_argument('--force', action='store_true'); s.add_argument('--engine', default='auto', choices=['auto','latexmk','xelatex','tectonic']); s.set_defaults(fn=cmd_latex_paper_compile)
    s = sub.add_parser('final-gate-check'); s.add_argument('case'); s.add_argument('--allow-warnings', action='store_true'); s.add_argument('--strict', action='store_true'); s.set_defaults(fn=cmd_final_gate)
    s = sub.add_parser('optimism-risk-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_optimism_risk)
    s = sub.add_parser('convergence-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_convergence)
    s = sub.add_parser('baseline-protocol-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_baseline_protocol)
    s = sub.add_parser('optimism-debt-report'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_optimism_debt)
    s = sub.add_parser('quality-oracle-v2'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_quality_oracle_v2)
    s = sub.add_parser('fast-result-validate'); s.add_argument('case'); s.add_argument('--path'); s.set_defaults(fn=cmd_fast_result_validate)
    s = sub.add_parser('agent-task-generate'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--phase', default='all'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_agent_task_generate)
    s = sub.add_parser('agent-protocol-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action='store_true'); s.set_defaults(fn=cmd_agent_protocol_check)
    s = sub.add_parser('problem-parse-review'); s.add_argument('case'); s.add_argument('--apply', action='store_true'); s.add_argument('--require-passed', action='store_true'); s.set_defaults(fn=cmd_problem_parse_review)
    s = sub.add_parser('problem-parse-apply-review'); s.add_argument('case'); s.set_defaults(fn=cmd_problem_parse_apply_review)
    s = sub.add_parser('verifier-scaffold'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_verifier_scaffold)
    s = sub.add_parser('verifier-run'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--abs-tol', type=float, default=1e-6); s.add_argument('--rel-tol', type=float, default=0.05); s.add_argument('--timeout', type=int, default=30); s.set_defaults(fn=cmd_verifier_run)
    s = sub.add_parser('verifier-compare'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action='store_true'); s.set_defaults(fn=cmd_verifier_compare)
    s = sub.add_parser('paper-build'); s.add_argument('case'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_paper_build)
    s = sub.add_parser('paper-quality-check'); s.add_argument('case'); s.add_argument('--strict', action='store_true'); s.set_defaults(fn=cmd_paper_quality_check)
    s = sub.add_parser('case-autopilot'); s.add_argument('case'); s.add_argument('--execute', action='store_true'); s.add_argument('--budget', default='regression'); s.add_argument('--resume', action='store_true'); s.add_argument('--package', action='store_true'); s.add_argument('--allow-warnings', action='store_true'); s.add_argument('--continue-on-failure', action='store_true'); s.set_defaults(fn=cmd_case_autopilot)

    s = sub.add_parser('contest-strategy-plan'); s.add_argument('case'); s.add_argument('--target', default='first_prize'); s.add_argument('--budget', default='full'); s.add_argument('--rounds', type=int, default=3); s.set_defaults(fn=cmd_contest_strategy)
    s = sub.add_parser('problem-intelligence'); s.add_argument('case'); s.add_argument('--target', default='first_prize'); s.set_defaults(fn=cmd_problem_intelligence)
    s = sub.add_parser('modeling-tournament'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--target', default='first_prize'); s.set_defaults(fn=cmd_modeling_tournament)
    s = sub.add_parser('modeling-readiness-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action=argparse.BooleanOptionalAction, default=True); s.set_defaults(fn=cmd_modeling_readiness)
    s = sub.add_parser('solver-factory'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_solver_factory)
    s = sub.add_parser('solver-build'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--force', action='store_true'); s.add_argument('--from', dest='from_source'); s.add_argument('--from-compiled-protocol', dest='from_compiled_protocol', action='store_true'); s.set_defaults(fn=cmd_solver_factory)
    s = sub.add_parser('solver-benchmark'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--strict', action='store_true'); s.add_argument('--min-variants', type=int, default=2); s.set_defaults(fn=cmd_solver_benchmark)
    s = sub.add_parser('verifier-factory'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--force', action='store_true'); s.add_argument('--target', default='first_prize'); s.set_defaults(fn=cmd_verifier_factory)
    s = sub.add_parser('paper-plan'); s.add_argument('case'); s.add_argument('--target', default='first_prize'); s.set_defaults(fn=cmd_paper_plan)
    s = sub.add_parser('figure-plan'); s.add_argument('case'); s.add_argument('--target', default='first_prize'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_figure_plan)
    s = sub.add_parser('paper-polish'); s.add_argument('case'); s.add_argument('--target', default='first_prize'); s.set_defaults(fn=cmd_paper_polish)
    s = sub.add_parser('judge-simulate'); s.add_argument('case'); s.add_argument('--rounds', type=int, default=3); s.add_argument('--target', default='first_prize'); s.set_defaults(fn=cmd_judge_simulate)
    s = sub.add_parser('improvement-loop'); s.add_argument('case'); s.add_argument('--rounds', type=int, default=2); s.add_argument('--target', default='first_prize'); s.set_defaults(fn=cmd_improvement_loop)
    s = sub.add_parser('first-prize-gate-check'); s.add_argument('case'); s.add_argument('--target-score', type=float, default=82.0); s.add_argument('--strict-final', action='store_true'); s.set_defaults(fn=cmd_first_prize_gate)
    s = sub.add_parser('first-prize-autopilot'); s.add_argument('case'); s.add_argument('--execute', action='store_true'); s.add_argument('--budget', default='full'); s.add_argument('--rounds', type=int, default=3); s.add_argument('--package', action='store_true'); s.add_argument('--continue-on-failure', action='store_true'); s.set_defaults(fn=cmd_first_prize_autopilot)
        # v7.2: Chart digitizer commands (on-demand, not core workflow)
    s = sub.add_parser('chart-gaps'); s.add_argument('case'); s.set_defaults(fn=cmd_chart_gaps)
    s = sub.add_parser('chart-digitize'); s.add_argument('case'); s.add_argument('--figure', default=None); s.add_argument('--dpi', type=int, default=200); s.add_argument('--debug', action='store_true'); s.set_defaults(fn=cmd_chart_digitize)
    s = sub.add_parser('chart-status'); s.add_argument('case'); s.set_defaults(fn=cmd_chart_status)

    s = sub.add_parser('chart-vision-calibrate'); s.add_argument('case'); s.add_argument('--image', required=True); s.add_argument('--save', action='store_true'); s.set_defaults(fn=cmd_chart_vision_calibrate)

    s = sub.add_parser('competition-autopilot'); s.add_argument('case'); s.add_argument('--target', default='national_first'); s.add_argument('--execute', action='store_true'); s.add_argument('--budget', default='full'); s.set_defaults(fn=cmd_competition_autopilot)
    # v7 stable aliases used by README / workflow docs
    s = sub.add_parser('final-gate'); s.add_argument('case'); s.add_argument('--allow-warnings', action='store_true'); s.add_argument('--strict', action='store_true'); s.set_defaults(fn=cmd_final_gate)
    s = sub.add_parser('package-submit'); s.add_argument('case'); s.add_argument('--allow-warnings', action='store_true'); s.set_defaults(fn=cmd_package_submit)


    # v9.0 Modeling OS commands
    s = sub.add_parser('experiment-record'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_experiment_record)
    s = sub.add_parser('experiment-pack'); s.add_argument('case'); s.set_defaults(fn=cmd_experiment_pack)
    s = sub.add_parser('evidence-pack-v2'); s.add_argument('case'); s.set_defaults(fn=cmd_evidence_pack_v2)
    s = sub.add_parser('claim-check'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_claim_check)
    s = sub.add_parser('skill-list'); s.set_defaults(fn=cmd_skill_list)
    s = sub.add_parser('skill-show'); s.add_argument('skill'); s.set_defaults(fn=cmd_skill_show)
    s = sub.add_parser('skill-run'); s.add_argument('case'); s.add_argument('--skill', required=True); s.set_defaults(fn=cmd_skill_run)
    s = sub.add_parser('skill-check'); s.add_argument('case'); s.add_argument('--skill', required=True); s.set_defaults(fn=cmd_skill_check)
    s = sub.add_parser('routing-check'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_routing_check)
    s = sub.add_parser('routing-promote'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_routing_promote)
    s = sub.add_parser('validator-build'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--from', dest='from_source'); s.add_argument('--from-compiled-protocol', dest='from_compiled_protocol', action='store_true'); s.set_defaults(fn=cmd_validator_build)
    s = sub.add_parser('validator-test'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_validator_test)
    s = sub.add_parser('negative-test'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_negative_test)
    s = sub.add_parser('capability-list'); s.set_defaults(fn=cmd_capability_list)
    s = sub.add_parser('capability-show'); s.add_argument('capability'); s.set_defaults(fn=cmd_capability_show)
    s = sub.add_parser('context-build'); s.add_argument('case'); s.add_argument('--task', required=True); s.set_defaults(fn=cmd_context_build)
    s = sub.add_parser('context-check'); s.add_argument('case'); s.set_defaults(fn=cmd_context_check)
    s = sub.add_parser('context-compact'); s.add_argument('case'); s.set_defaults(fn=cmd_context_compact)
    s = sub.add_parser('quality-review'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_quality_review)
    s = sub.add_parser('red-team-gate'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_red_team_gate)
    s = sub.add_parser('model-readiness-gate'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_model_readiness_gate)
    s = sub.add_parser('verified-candidate-comparison'); s.add_argument('case'); s.add_argument('--question'); s.set_defaults(fn=cmd_verified_candidate_comparison)
    s = sub.add_parser('mcp-safe-check'); s.add_argument('case'); s.add_argument('--tool-class', required=True); s.add_argument('--target'); s.add_argument('--query'); s.add_argument('--source-url'); s.add_argument('--used-for', default='method_advisory'); s.set_defaults(fn=cmd_mcp_safe_check)


    # v10 Constraint-certified OS commands
    s = sub.add_parser('constraint-ledger-build'); s.add_argument('case'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_constraint_ledger_build)
    s = sub.add_parser('constraint-ledger-check'); s.add_argument('case'); s.set_defaults(fn=cmd_constraint_ledger_check)
    s = sub.add_parser('constraint-coverage-check'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_constraint_coverage_check)
    s = sub.add_parser('constraint-promote'); s.add_argument('case'); s.set_defaults(fn=cmd_constraint_promote)
    s = sub.add_parser('dependency-graph-build'); s.add_argument('case'); s.add_argument('--force', action='store_true'); s.set_defaults(fn=cmd_dependency_graph_build)
    s = sub.add_parser('dependency-check'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_dependency_check)
    s = sub.add_parser('dependency-report'); s.add_argument('case'); s.set_defaults(fn=cmd_dependency_report)
    s = sub.add_parser('certificate-build'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--from', dest='from_source'); s.set_defaults(fn=cmd_certificate_build)
    s = sub.add_parser('certificate-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_certificate_check)
    s = sub.add_parser('certificate-report'); s.add_argument('case'); s.set_defaults(fn=cmd_certificate_report)
    s = sub.add_parser('validator-adequacy-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_validator_adequacy_check)
    s = sub.add_parser('adversarial-test-build'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_adversarial_test_build)
    s = sub.add_parser('adversarial-test-run'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_adversarial_test_run)
    s = sub.add_parser('semantic-redteam'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_semantic_redteam)
    s = sub.add_parser('missing-constraint-probe'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_missing_constraint_probe)
    s = sub.add_parser('overclaim-check'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_overclaim_check)
    s = sub.add_parser('model-risk-register'); s.add_argument('case'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_model_risk_register)
    s = sub.add_parser('model-risk-check'); s.add_argument('case'); s.set_defaults(fn=cmd_model_risk_check)
    s = sub.add_parser('independent-verify-protocol'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_independent_verify_protocol)
    s = sub.add_parser('verified-candidate-comparison-v2'); s.add_argument('case'); s.set_defaults(fn=cmd_verified_candidate_comparison_v2)
    s = sub.add_parser('final-gate-v2'); s.add_argument('case'); s.add_argument('--strict', action='store_true', default=True); s.set_defaults(fn=cmd_final_gate_v2)
    s = sub.add_parser('prompt-profile-list'); s.set_defaults(fn=cmd_prompt_profile_list)
    s = sub.add_parser('prompt-profile-show'); s.add_argument('profile'); s.set_defaults(fn=cmd_prompt_profile_show)
    s = sub.add_parser('task-card-build'); s.add_argument('case'); s.add_argument('--role', required=True); s.add_argument('--question'); s.add_argument('--profile', default='modeling_agent_strict_v10'); s.add_argument('--phase', default='full_case'); s.set_defaults(fn=cmd_task_card_build)
    s = sub.add_parser('failure-ledger-add'); s.add_argument('case'); s.add_argument('--command', default='unknown'); s.add_argument('--return-code', type=int, default=1); s.add_argument('--stdout', default=''); s.add_argument('--stderr', default=''); s.add_argument('--root-cause', default='unknown'); s.set_defaults(fn=cmd_failure_ledger_add)
    s = sub.add_parser('repair-check'); s.add_argument('case'); s.set_defaults(fn=cmd_repair_check_v10)
    s = sub.add_parser('migrate-case-to-v10'); s.add_argument('case'); s.add_argument('--mode', default='strict_recommended'); s.set_defaults(fn=cmd_migrate_case_to_v10)
    s = sub.add_parser('case-policy-set'); s.add_argument('case'); s.add_argument('--strictness', default='strict_recommended', choices=['legacy_compatible','strict_recommended','strict_required']); s.set_defaults(fn=cmd_case_policy_set)


    # v11 Dynamic Protocol OS commands
    s = sub.add_parser('problem-type-infer'); s.add_argument('case'); s.set_defaults(fn=cmd_problem_type_infer)
    s = sub.add_parser('capability-atom-match'); s.add_argument('case'); s.set_defaults(fn=cmd_capability_atom_match)
    s = sub.add_parser('protocol-synthesize'); s.add_argument('case'); s.add_argument('--from', dest='from_source', default='capability-atoms'); s.set_defaults(fn=cmd_protocol_synthesize)
    s = sub.add_parser('protocol-lint'); s.add_argument('case'); s.set_defaults(fn=cmd_protocol_lint)
    s = sub.add_parser('protocol-redteam'); s.add_argument('case'); s.set_defaults(fn=cmd_protocol_redteam)
    s = sub.add_parser('protocol-compile'); s.add_argument('case'); s.set_defaults(fn=cmd_protocol_compile)
    s = sub.add_parser('dynamic-protocol-gate'); s.add_argument('case'); s.add_argument('--strict', action='store_true', default=True); s.set_defaults(fn=cmd_dynamic_protocol_gate)
    s = sub.add_parser('negative-test-build'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--from', dest='from_source'); s.add_argument('--from-compiled-protocol', dest='from_compiled_protocol', action='store_true'); s.set_defaults(fn=cmd_negative_test_build)
    s = sub.add_parser('mutation-test-build'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--from', dest='from_source'); s.add_argument('--from-compiled-protocol', dest='from_compiled_protocol', action='store_true'); s.set_defaults(fn=cmd_mutation_test_build)
    s = sub.add_parser('validator-adequacy-check-v2'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_validator_adequacy_check_v2)
    s = sub.add_parser('model-fidelity-plan-build'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.add_argument('--from', dest='from_source'); s.add_argument('--from-compiled-protocol', dest='from_compiled_protocol', action='store_true'); s.set_defaults(fn=cmd_model_fidelity_plan_build)
    s = sub.add_parser('claim-limit-check'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_claim_limit_check)
    s = sub.add_parser('fidelity-report'); s.add_argument('case'); s.set_defaults(fn=cmd_fidelity_report)
    s = sub.add_parser('certificate-plan-synthesize'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_certificate_plan_synthesize)
    s = sub.add_parser('certificate-check-v2'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_certificate_check_v2)
    s = sub.add_parser('claim-certificate-bind'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_claim_certificate_bind)
    s = sub.add_parser('output-template-infer'); s.add_argument('case'); s.set_defaults(fn=cmd_output_template_infer)
    s = sub.add_parser('output-schema-synthesize'); s.add_argument('case'); s.set_defaults(fn=cmd_output_schema_synthesize)
    s = sub.add_parser('output-schema-check'); s.add_argument('case'); s.set_defaults(fn=cmd_output_schema_check)
    s = sub.add_parser('workbook-schema-validate'); s.add_argument('case'); s.add_argument('--all-required', action='store_true'); s.set_defaults(fn=cmd_workbook_schema_validate)
    s = sub.add_parser('independent-solver-synthesize'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_independent_solver_synthesize)
    s = sub.add_parser('heterogeneous-verify'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_heterogeneous_verify)
    s = sub.add_parser('discrepancy-report'); s.add_argument('case'); s.add_argument('--question'); s.add_argument('--all', action='store_true'); s.set_defaults(fn=cmd_discrepancy_report)
    s = sub.add_parser('gate-escape-risk-check'); s.add_argument('case'); s.set_defaults(fn=cmd_gate_escape_risk_check)
    s = sub.add_parser('capability-gap-matrix'); s.add_argument('case'); s.set_defaults(fn=cmd_capability_gap_matrix)
    s = sub.add_parser('protocol-reuse-suggest'); s.add_argument('case'); s.set_defaults(fn=cmd_protocol_reuse_suggest)
    s = sub.add_parser('os-improvement-report'); s.add_argument('case'); s.set_defaults(fn=cmd_os_improvement_report)
    s = sub.add_parser('final-gate-v3'); s.add_argument('case'); s.add_argument('--strict', action='store_true', default=True); s.set_defaults(fn=cmd_final_gate_v3)

    return p


